### ISSUE TITLE
Light sensor is not working

### ISSUE THREAD

**Issue by devilsray** [soef/ioBroker.mysensors-2#2]
Hello,

my light sensors are not working. In log there is:

 Got from Serial: 1; 2; C_SET; ACK_FALSE; V_LIGHT_LEVEL; 100

but no values are available in objects browser. Temperature is working. For comparison the serial log:

Got from Serial: 1; 1; C_SET; ACK_FALSE; V_TEMP; 21.5

**Comment by soef** [comment]
Did try to refresh the objects browser? The log looks good. Otherwise delete the light object in the objects browser and aktivate the debug log level.

**Comment by devilsray** [comment]
Hello,

i deleted the objects up to the main folder of mysensors and refreshed it. Same problem. I add some screenshots 

[image1](http://devilsray.com/images/list1.png)
[image2](http://devilsray.com/images/list2.png)

**Comment by devilsray** [comment]
Hello,

perhaps good news. Another sketch is working fine. I will debug it and report here

**Comment by devilsray** [comment]
Other sketch is not working after restart. Unfortunately there is not enough time for me to debug this problem. Perhaps something on my constellation is wrong. I close the ticket. If something else has also this problem, please reopen.
