### ISSUE TITLE
Getting an Error on IOBroker on a Pi2

### ISSUE THREAD

**Issue by Zipkart** [soef/ioBroker.mysensors-2#3]
On my RasPi 3 the adapter works fine.

Then i wanted to try it in my production system. the System uses USB0 für der Serial gateway. the adapter starts and then an error appears in the log and the gateway did't connect.

the following error occurs

`Cannot open serial port "/dev/ttyUSB0": TypeError: `openImmediately` is now called `autoOpen` and is a property of options`

this is the complete Logtext

`
mysensors-2.0	2017-02-11 07:54:12.987	error	Cannot open serial port "/dev/ttyUSB0": TypeError: `openImmediately` is now called `autoOpen` and is a property of options
mysensors-2.0	2017-02-11 07:54:12.463	info	starting. Version 2.0.20 in /opt/iobroker/node_modules/iobroker.mysensors-2, node: v4.7.2`

**Comment by soef** [comment]
Hello, don'I think that this is problem of the mysensors-2 adapter.  On my site the Adapter runs on a rpi2. My node version is 4.7.2.

**Comment by Zipkart** [comment]
Thanks a lot for your answer.  Today i found my error. 

It was because of a wrong serialport Version. I Hand installes a Version 4.2.0 and The older version 3.1.2 was Necessary. After Downgrade the serialport the Adapter is Workung Fine.

**Comment by soef** [comment]
Nice to hear!
