### ISSUE TITLE
Problem with MySensor LUX Node 

### ISSUE THREAD

**Issue by Zipkart** [soef/ioBroker.mysensors-2#4]
Hello.
I'm using a Arduino node with the Light-lux sketch an fixed node ID. Under the serial Monitor the node presents itsefls and is connected to the gateway.
In iobroker i can't find the node. wether the node id nor the Arduino is shown.

is ist possible that the iobroker adapter doesn't accepts light lux sensors.

i'm not sure if this is the correctt place to ask such questions. when it is the wrong place i would be glad to here from you.

thanks

und Schönen Tag noch

Stefan

**Comment by soef** [comment]
Hello, how does the presentation of your node look like? Did you activate the inclusion mode before starting your node (in configuration oder by setting mysensors-2.0.commands.inclusionOn to true)?

PS: Wenn du auch aus Deutschland bist, können wir auch deutsch schreiben.

Grüße.

**Comment by Zipkart** [comment]
Hallo und guten Abend.

ich versuche mal ein wenig zu sammeln. Das ist die Fehlermeldung in IO Broker.

ID not found. Inclusion mode OFF: {"id":"51","childId":"0","type":"C_SET","ack":false,"subType":"V_LEVEL","payload":"13","num":{"type":1,"subType":37,"id":51,"childId":0}}

Komischerweise sagt er dort das inclusive Mode OFF sei. Ich habe aber mehrfach über die Adapter Settings sowie auch über die Objekte in IO Broker den Inclusive Mode eingeschaltet.

Als Gateway benutze ich einen Arduino NANO serial Gateway mit Mysensors  Version 2

Ich bekomme auch vom DHT Skript, welcher auf dem Gateway verbaut ist die Meldung Cannot Parse Data on Child 0 und 1. Er zeigt die Temperatur und die Luftfeuchte trotzdem an.


Hier der Presentation Teil:

void presentation()  {
  // Send the sketch version information to the gateway and Controller
  sendSketchInfo("Light Lux Sensor", "1.0");
  //Send the sensor node sketch version information to the gateway
  sendSketchInfo("Repeater Node", "1.0");

  // Register all sensors to gateway (they will be created as child devices)
  present(CHILD_ID_LIGHT, S_LIGHT_LEVEL);
}


Hier nun noch mein Sketch für den Lichtsensor.

// Enable debug prints to serial monitor
#define MY_DEBUG 

#define MY_REPEATER_FEATURE
#define MY_NODE_ID 51


// Enable and select radio type attached
#define MY_RADIO_NRF24
//#define MY_RADIO_RFM69

#include <SPI.h>
#include <MySensors.h>  
#include <BH1750.h>
#include <Wire.h>

#define CHILD_ID_LIGHT 0
unsigned long SLEEP_TIME = 5000; // Sleep time between reads (in milliseconds)

BH1750 lightSensor;

// V_LIGHT_LEVEL should only be used for uncalibrated light level 0-100%.
// If your controller supports the new V_LEVEL variable, use this instead for
// transmitting LUX light level.
// MyMessage msg(CHILD_ID_LIGHT, V_LIGHT_LEVEL);
MyMessage msg(CHILD_ID_LIGHT, V_LEVEL);  
uint16_t lastlux;

void setup()  
{ 
  lightSensor.begin();
}

void presentation()  {
  // Send the sketch version information to the gateway and Controller
  sendSketchInfo("Light Lux Sensor", "1.0");
  //Send the sensor node sketch version information to the gateway
  sendSketchInfo("Repeater Node", "1.0");

  // Register all sensors to gateway (they will be created as child devices)
  present(CHILD_ID_LIGHT, S_LIGHT_LEVEL);
}

void loop()      
{     
  uint16_t lux = lightSensor.readLightLevel();// Get Lux value
  Serial.println(lux);
  if (lux != lastlux) {
      send(msg.set(lux));
      lastlux = lux;
  }

  sleep(SLEEP_TIME);
}

Ich hoffe die Daten helfen Dir.

Gruß
Stefan

ps:
Da ich beim Zusammenbauen keinen IOBroker hatte musste ich auf dem MAcBook Domoticz einsatllieren. Dort wird der Sensor normal erkannt und angezeigt. Auch mit ID 51

**Comment by soef** [comment]
Hallo, ich habe dein Sketch einmal verwendet und es wurde ein Gerät mit Node-ID 51 und zwei Datenpunkten (V_LEVEL und V_LIGHT_LEVEL) angelegt. Stelle temporär einmal den "Anlernen-Timeout" in der Konfiguration auf 0 und aktiviere den Anlernmodus erneut. Ansonsten wird der Anlernmodus nach dem eingetragenen Timeout wieder beendet.

**Comment by Zipkart** [comment]
Super. 

Ich werde es mal probieren. 

Stefan Schmid

**Comment by Zipkart** [comment]
Guten Morgen.

Sorry dass ich mich erst jetzt melde. Aber ich hätte ziemlichen Stress mit meinem iobroker und anderen Problemchen im SmartHome 😉

Gestern habe ich es aber geschafft den Sketch nochmal neunaufzuspielen.  Jetzt hat er ihn auch erkannt. Ich bin. Ich sicher ob es am neuen aufspielen, oder am zweiten NRF Chip lag.

Trotzdem nochmals vielen Dank. 

Stefan Schmid
Josef-Spehl-Str. 43
52525 Heinsberg

(0173) 98 00 531
